<?php

/**
 * Generated on Tue, 26 Aug 2025 10:50:14
 * Part moTV.eu SDK integration kit
 */

declare(strict_types=1);

namespace Motv\Connector\Sms\InputEntities;

class MotvEntity
{
}


namespace Motv\Connector\Sms\InputEntities\ApiSupport;

class ApiCallEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $url;
	public string $method;

	/** @var array<mixed> */
	public array $data;
	public array $headers;
	public ?string $response;
	public ?float $time;
}

class RoleEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $roles_name;
	public bool $roles_active;
}

class UserEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public ?string $users_email;
	public ?string $users_password;
	public ?int $users_roles_id;
	public ?bool $users_active;
	public ?string $users_image;
}

class WhereEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $column;
	public \Motv\Connector\Sms\Enums\ApiSupport\WhereTypeEnum $type;
	public \Motv\Connector\Sms\Enums\ApiSupport\WhereValueTypeEnum $valueType;
	public $value;
}


namespace Motv\Connector\Sms\InputEntities\Sms;

class BouquetEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $bouquets_name;
	public string $bouquets_conax_id;
	public bool $bouquets_is_active;
	public ?string $bouquets_detail;
	public \Motv\Connector\Sms\Enums\Sms\DeviceEnum $bouquets_network;
}

class CategoryEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $categories_name;
	public \Motv\Connector\Sms\Enums\Sms\CategoriesTypeEnum $categories_type;
	public ?string $categories_query;
	public bool $categories_active;
}

class CsvXlsColumnEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public int $date_start;
	public ?int $date_end;
	public bool $date_end_next;
	public ?int $start;
	public ?int $end;
	public bool $end_next;
	public ?int $duration;
	public int $title;
	public ?int $sub_title;
	public ?int $description;
	public ?int $rating;
	public ?int $category;
	public ?int $episode_num;
}

class CustomerContactEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $viewers_contact_type;
	public string $viewers_contact_content;
}

class CustomerNoteEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $viewers_note_text;
	public int $viewers_note_viewers_id;
}

class DataBundleEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $data_bundles_internal_name;
	public ?string $data_bundles_name;
	public ?string $data_bundles_code;
}

class DealerEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $dealers_name;
	public bool $dealers_active;
	public ?bool $dealers_infinite_credit;
	public ?bool $dealers_any_card;
	public ?int $dealers_dealers_id;
	public ?string $dealers_codename;
	public ?string $dealers_phone;
	public ?string $dealers_address;
	public ?string $dealers_hours;
	public ?string $dealers_lat;
	public ?string $dealers_long;
	public ?string $dealers_email;
	public ?float $dealers_commission;
	public ?string $dealers_image;
}

class DeviceAppleEntity extends DeviceEntity
{
	public ?int $device_apple_viewers_id;
	public string $device_apple_email;
	public string $device_apple_generated_id;
	public string $device_apple_identity_token;
	public string $device_apple_authorization_code;
}

class DeviceCardlessCryptoguardEntity extends DeviceEntity
{
	public ?int $device_cardless_cryptoguard_viewers_id;
	public ?string $device_cardless_cryptoguard_smartcard_id;
	public ?string $device_cardless_cryptoguard_note;
	public ?int $device_cardless_cryptoguard_network;
}

class DeviceEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
}

class DeviceFacebookEntity extends DeviceEntity
{
	public ?int $device_facebook_viewers_id;
	public string $device_facebook_email;
	public string $device_facebook_generated_id;
}

class DeviceGoogleEntity extends DeviceEntity
{
	public ?int $device_google_viewers_id;
	public string $device_google_email;
}

class DeviceIrdetoEntity extends DeviceEntity
{
	public ?int $device_irdeto_viewers_id;
	public int $device_irdeto_serial;
	public ?string $device_irdeto_note;
}

class DeviceMotvEntity extends DeviceEntity
{
	public ?int $device_motv_viewers_id;
	public ?string $device_motv_login;
	public ?int $device_motv_motv_portals_id;
	public ?int $device_motv_motv_id;
	public ?int $device_motv_profiles_id;
	public ?string $device_motv_password;
	public ?string $device_motv_name;
	public ?string $device_motv_pin;
	public ?string $device_motv_birthday;
	public ?string $device_motv_image;
	public ?array $device_motv_mac;
	public ?bool $device_motv_social_registration_completed;
	public ?bool $device_motv_autogenerated;
}

class DevicePairedCryptoguardEntity extends DeviceEntity
{
	public ?int $device_paired_cryptoguard_viewers_id;
	public ?int $device_paired_cryptoguard_smartcard_id;
	public ?int $device_paired_cryptoguard_settopbox_id;
	public ?string $device_paired_cryptoguard_note;
	public ?int $device_paired_cryptoguard_network;
}

class EmailEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	/** @var array<string> */
	public array $to;

	/** @var array<string> */
	public array $cc;

	/** @var array<string> */
	public array $bcc;

	/** @var array<string> */
	public array $attachements;
	public string $subject;
	public string $body;
}

class EpgEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public ?int $epg_tv_number;
	public string $epg_name;
	public string $epg_dirname;
	public \Motv\Connector\Sms\Enums\Sms\EpgSourceEnum $epg_source;
	public \Motv\Connector\Sms\Enums\Sms\EpgFormatEnum $epg_format;
	public float $epg_timeshift;
	public \Motv\Connector\Sms\Enums\Sms\EpgFrequencyCheckEnum $epg_frequency_check;
	public ?\Motv\Connector\Sms\Enums\Sms\DelimiterEnum $epg_delimeter;
	public ?string $epg_sheet_index;
	public bool $epg_dayfirst;
	public ?string $epg_imap_server;
	public ?string $epg_imap_username;
	public ?string $epg_imap_password;
	public ?string $epg_ftp_server;
	public ?string $epg_ftp_username;
	public ?string $epg_ftp_password;
	public ?string $epg_ftp_folder;
	public ?string $epg_ftp_file_name;
	public ?string $epg_http_address;
	public ?int $epg_http_days;
	public ?string $epg_data_starts;
	public bool $epg_active;
	public ?string $epg_xml_tag;
	public ?string $epg_xml_channel_id;
	public ?string $epg_xml_channel_tag;
	public ?string $epg_xml_custom_xpath;
	public ?bool $epg_http_date;
	public ?\Motv\Connector\Sms\Enums\Sms\EpgDatetimeFormatEnum $epg_duration_format;
	public ?string $epg_webgrab_config;
	public ?int $epg_webgrab_days;
	public ?bool $epg_http_zip_archive;
	public ?string $epg_http_filename;
	public ?string $epg_http_username;
	public ?string $epg_http_password;
	public bool $epg_disregard_date_tz;
	public ?array $epg_mw_channels_ids;
}

class EpgEventEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	/** @var \DateTimeImmutable|string */
	public $epg_events_start;

	/** @var \DateTimeImmutable|string */
	public $epg_events_end;
	public string $epg_events_title;
	public ?string $epg_events_subtitle;
	public ?string $epg_events_category;
	public ?string $epg_events_desc;
	public ?string $epg_events_rating;
	public ?string $epg_events_episode_num;
}

class EpgEventsImageEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $epg_events_images_epg_events_title;
	public int $epg_events_images_epg_id;
	public ?string $epg_events_images_name;
}

class GroupActionEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $group_action_name;
	public \Motv\Connector\Sms\Enums\Sms\GroupActionTypeEnum $group_action_type;
	public string $group_action_query;
	public bool $group_action_file;

	/** @var array<int> */
	public array $group_action_roles;
}

class GroupsInvoiceEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $groups_invoices_mtext;
	public string $groups_invoices_name;
	public string $groups_invoices_text;
}

class ImapEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $config_imap_servers_name;
	public string $config_imap_servers_host;
	public bool $config_imap_servers_active;
	public int $config_imap_servers_port;
	public string $config_imap_servers_login;
	public string $config_imap_servers_password;
	public ?string $config_imap_servers_description;
	public \Motv\Connector\Sms\Enums\Sms\SmtpSecureTypeEnum $config_imap_servers_secure;
}

class InvoiceEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public \Motv\Connector\Sms\Enums\Sms\InvoiceTypeEnum $invoice_type;
	public \Motv\Connector\Sms\Enums\Sms\InvoiceStateEnum $invoice_state;
	public float $invoice_price;
	public float $invoice_price_retail;
	public ?float $invoice_due;
	public ?string $invoice_remark;
	public string $invoice_currencies_code;
}

class LogEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public int $log_int_parameter1;
	public ?int $log_int_parameter2;
	public ?int $log_viewers_id;
	public ?string $log_string_parameter1;
	public ?string $log_string_parameter2;
	public ?string $log_string_parameter3;
	public ?string $log_text_parameter;
}

class MotvCustomerAcountLabelsEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	/** @var array<MotvRegistrationFormLabelEntity> */
	public array $loginLabels;

	/** @var array<MotvRegistrationFormLabelEntity> */
	public array $passwordLabels;

	/** @var array<MotvRegistrationFormLabelEntity> */
	public array $passwordRepeatLabels;

	/** @var array<MotvRegistrationFormLabelEntity> */
	public array $pinLabels;
	public bool $motvLoginIsEmail;
	public bool $motvRegistrationPinRequired;
	public bool $motvRegistrationShowPin;
}

class MotvCustomerInfoGroupLabelsEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	/** @var array<MotvRegistrationFormLabelEntity> */
	public array $motvSectionLabels;

	/** @var array<MotvRegistrationFormLabelEntity> */
	public array $generalSectionLabels;

	/** @var array<MotvRegistrationFormLabelEntity> */
	public array $contactSectionLabels;

	/** @var array<MotvRegistrationFormLabelEntity> */
	public array $addressSectionLabels;
}

class MotvPortalEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $motv_portals_name;
	public int $motv_portals_dealers_id;
	public ?string $motv_portals_url;
	public int $motv_portals_motv_vendors_id;
	public ?int $motv_portals_config_smtp_servers_id;
	public \Motv\Connector\Sms\Enums\Sms\MotvPortalRegistrationMethodEnum $motv_portals_registration_method;
	public array $motv_portals_sections;

	/** @var array<\Motv\Connector\Sms\Enums\Sms\MotvPortalSocialSiteEnum> */
	public array $motv_portals_social_sites;
	public ?string $motv_portals_google_client_id;
	public ?string $motv_portals_facebook_client_id;
	public ?string $motv_portals_facebook_secret;
	public bool $motv_portals_registration_enabled;
	public \Motv\Connector\Sms\Enums\Sms\MotvPortalIOSRegistrationEnabledEnum $motv_portals_ios_registration_enabled;
	public bool $motv_portals_account_update_enabled;
	public ?string $motv_portals_custom_registration_close;
	public ?string $motv_portals_custom_registration_open;
	public ?string $motv_portals_custom_lost_password_close;
	public ?string $motv_portals_custom_lost_password_open;
	public ?string $motv_portals_custom_purchase_close;
	public ?string $motv_portals_custom_purchase_open;
	public ?string $motv_portals_google_gtm;
	public ?string $motv_portals_section_homepage_url;
	public ?string $motv_portals_section_apps_url;
	public ?string $motv_portals_section_live_url;
	public ?string $motv_portals_section_radio_url;
	public ?string $motv_portals_section_recordings_url;
	public ?string $motv_portals_section_vod_url;
	public ?string $motv_portals_terms_url;
	public ?string $motv_portals_privacy_url;
	public ?string $motv_portals_contact_url;
	public int $motv_portals_registration_template;
	public int $motv_portals_lost_password_template;
	public int $motv_portals_lost_pin_template;
	public int $motv_portals_avatar;
	public bool $motv_portals_lost_password_enabled;
	public ?string $motv_portals_portal_apple_client_id;
	public ?int $motv_portals_welcome_template;
	public ?int $motv_portals_registration_text_template;
	public bool $motv_portals_show_subscription_section;
	public ?int $motv_portals_test_viewers_id;

	/** @var array<int> */
	public array $motv_portals_users;
}

class MotvPortalPageEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public int $motv_portals_pages_motv_portal_id;
	public string $motv_portals_pages_url_name;
	public ?string $motv_portals_pages_description;
	public string $motv_portals_pages_content;
	public string $motv_portals_pages_title;
	public ?\Motv\Connector\Sms\Enums\Sms\PortalPageTypeEnum $motv_portals_pages_type;
	public ?string $motv_portals_pages_language;
}

class MotvRegistrationFormAddressTypeEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $registration_form_address_types_type;

	/** @var array<MotvRegistrationFormLabelEntity> */
	public array $labels;
	public ?int $registration_form_address_types_max;
	public ?int $registration_form_address_types_min;
}

class MotvRegistrationFormControlEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public \Motv\Connector\Sms\Enums\Sms\MotvRegistrationFormSectionEnum $registration_form_controls_section;
	public string $registration_form_controls_column_type;

	/** @var array<MotvRegistrationFormLabelEntity> */
	public array $labels;
	public \Motv\Connector\Sms\Enums\Sms\CustomerFieldTypeEnum $registration_form_controls_type;
	public bool $registration_form_controls_optional;
	public ?int $registration_form_controls_max;
	public ?int $registration_form_controls_min;
	public ?\Motv\Connector\Sms\Enums\Sms\MotvRegistrationFormPaternEnum $registration_form_controls_pattern;
	public ?string $registration_form_controls_custom_pattern;
	public ?array $patternLabel;
	public ?\Motv\Connector\Sms\Enums\Sms\MotvRegistrationFormOptionEnum $registration_form_controls_options;
	public ?string $registration_form_controls_custom_options;
	public \Motv\Connector\Sms\Enums\Sms\MotvRegistrationFormUniqueEnum $registration_form_controls_unique;
	public bool $registration_form_controls_read_only;
	public ?int $registration_form_controls_order;
}

class MotvRegistrationFormEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $registration_form_default_language;
	public string $registration_form_contact_format;
	public string $registration_form_address_form_layout;
}

class MotvRegistrationFormLabelEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public ?\Motv\Connector\Sms\Enums\Sms\MotvRegistrationFormLabelSectionEnum $registration_form_labels_section;
	public string $registration_form_labels_language;
	public string $registration_form_labels_label;
	public bool $registration_form_labels_pattern_label;
}

class PaymentGatewayEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $payment_gateways_internal_name;
	public \Motv\Connector\Sms\Enums\Sms\PaymentGatewaysEnum $payment_gateways_type;
	public bool $payment_gateways_active;
	public string $payment_gateways_url;
	public string $payment_gateways_merchant_number;
	public ?string $payment_gateways_api_key;
	public ?string $payment_gateways_private_key;
	public ?string $payment_gateways_private_key_extension;
	public ?string $payment_gateways_private_key_password;
	public ?string $payment_gateways_public_key;
	public ?string $payment_gateways_public_key_extension;
	public ?string $payment_gateways_wsdl;
	public ?string $payment_gateways_wsdl_extension;
	public ?string $payment_gateways_provider;
	public ?string $payment_gateways_note;
	public ?string $payment_gateways_primary_key;
	public ?string $payment_gateways_users_id;
	public ?string $payment_gateways_gateway_key;
}

class ProductEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $products_name;
	public ?int $products_bouquets_id;
	public ?int $products_unit_length;
	public ?\Motv\Connector\Sms\Enums\Sms\TimeUnitEnum $products_unit;
	public ?int $products_hp_id;
	public bool $products_is_active;
	public int $products_products_groups_id;
	public bool $products_free_prepay;
	public \Motv\Connector\Sms\Enums\Sms\ProductTypeEnum $products_type;
	public \Motv\Connector\Sms\Enums\Sms\ProductPaymentTypeEnum $products_payment_type;
	public ?\Motv\Connector\Sms\Enums\Sms\SelfcareProductTypeEnum $products_selfcare_product_type;
	public ?array $products_devices;

	/** @var array<int> */
	public array $products_categories;
	public bool $products_hide_from_customer;
	public ?int $products_discount;

	/** @var \DateTimeImmutable|string|null */
	public $products_discount_from;

	/** @var \DateTimeImmutable|string|null */
	public $products_discount_to;
	public array $prices;
	public ?array $products_payment_gateways;
	public ?int $products_data_bundles_id;
}

class ProductsGroupEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $products_groups_name;
	public int $products_groups_groups_invoices_id;
	public bool $products_groups_open;
}

class ProductsPriceEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $products_prices_currencies_code;
	public float $products_prices_price_retail;
	public float $products_prices_price;
	public float $products_prices_tax;
	public ?float $products_prices_init_payment_price;
}

class ReportColumnEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $reports_columns_name;
	public \Motv\Connector\Sms\Enums\Sms\ReportFilterEnum $reports_columns_filter;
	public \Motv\Connector\Sms\Enums\Sms\ReportColumnTypeEnum $reports_columns_type;
}

class ReportEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $reports_name;
	public string $reports_query;

	/** @var array<int> */
	public array $reports_roles;

	/** @var array<ReportColumnEntity> */
	public array $reports_columns;

	/** @var array<ReportLinkEntity> */
	public array $reports_links;
}

class ReportLinkEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $reports_links_column_name;
	public \Motv\Connector\Sms\Enums\Sms\ReportLinkEnum $reports_links_link;
}

class ReportPrecalculationEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $reports_precalculations_name;
	public bool $reports_precalculations_generate;
	public string $reports_precalculations_query;
	public ?string $reports_precalculations_index;
}

class RequestsEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public \Motv\Connector\Sms\Enums\Sms\RequestTypeEnum $request_type;
	public string|int|null $request_smartcard_id;
	public ?string $request_box_number;

	/** @var \DateTimeImmutable|string|null */
	public $request_subscribe_from;

	/** @var \DateTimeImmutable|string|null */
	public $request_subscribe_to;
	public ?int $request_viewer_id;
	public ?int $request_bouquet_id;
	public bool $request_in_process;
	public bool $request_processed;
	public ?int $request_viewers_bouquets_id;
	public bool $request_filestatus;
	public ?int $request_request_batch_id;
	public bool $request_batchable;

	/** @var \DateTimeImmutable|string|null */
	public $request_processed_time;

	/** @var \DateTimeImmutable|string */
	public $request_created_time;
	public \Motv\Connector\Sms\Enums\Sms\DeviceEnum $request_cas;
	public ?string $request_data;
	public ?int $requests_id;
	public int $queue_priority;
}

class RightEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public int $roles_id;
	public int $rights_id;
}

class RoleDeviceActionsEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public \Motv\Connector\Sms\Enums\Sms\DeviceEnum $device;

	/** @var array<\Motv\Connector\Sms\Enums\Sms\RoleDeviceActionEnum> */
	public array $actions;
}

class RoleEntity extends \Motv\Connector\Sms\InputEntities\ApiSupport\RoleEntity
{
	public ?int $roles_roles_id;
}

class SalesInvoiceEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	/** @var array<SalesInvoiceProductEntity> */
	public array $products;
	public ?float $invoice_discount;
	public ?string $invoice_remark;
	public ?string $parameters;
	public ?string $remark;
	public ?int $print_copies;
	public ?string $email;
}

class SalesInvoiceProductEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public int $products_id;
	public \Motv\Connector\Sms\Enums\Sms\ProductContentTypeEnum $product_content_type;
	public ?int $quantity;
	public ?string $serial;

	/** @var \DateTimeImmutable|string|null */
	public $from;

	/** @var \DateTimeImmutable|string|null */
	public $to;
	public ?float $price_retail;
}

class ScheduleEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $schedule_name;
	public bool $schedule_active;
	public bool $schedule_recurrence;
	public ?int $schedule_repeat;
	public \Motv\Connector\Sms\Enums\Sms\TimeUnitEnum $schedule_repeat_unit;

	/** @var \DateTimeImmutable|string */
	public $schedule_start;

	/** @var \DateTimeImmutable|string */
	public $schedule_end;
	public int $schedule_group_action_id;
	public string $schedule_data;
	public ?string $image;
}

class SmtpServerEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $config_smtp_servers_name;
	public bool $config_smtp_servers_active;
	public ?int $config_smtp_servers_port;
	public \Motv\Connector\Sms\Enums\Sms\SmtpSecureTypeEnum $config_smtp_servers_secure;
	public string $config_smtp_servers_host;
	public string $config_smtp_servers_login;
	public string $config_smtp_servers_password;
	public ?string $config_smtp_servers_address_from;
	public string $config_smtp_servers_description;
}

class TicketEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public int $tickets_creation_users_id;
	public int $tickets_viewers_id;
	public string $tickets_note;

	/** @var \DateTimeImmutable|string */
	public $tickets_creation_time;

	/** @var \DateTimeImmutable|string|null */
	public $tickets_close_time;
	public ?int $tickets_status;
	public ?int $tickets_departments_id;
	public ?int $tickets_responsible_users_id;

	/** @var \DateTimeImmutable|string|null */
	public $tickets_departments_change_time;
	public bool $tickets_notifications_sent;
	public bool $tickets_visited;
	public ?int $tickets_tickets_priorities_id;
	public ?int $tickets_tickets_categories_id;
	public ?int $tickets_action;
	public ?string $tickets_action_parameters;
}

class TicketFileEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $tickets_files_file_name;
	public int $tickets_files_tickets_id;
	public string $tickets_files_file_type;
}

class TicketsCategoryEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $tickets_categories_name;
	public int $tickets_categories_departments_id;
	public ?int $tickets_categories_days;
	public ?int $tickets_categories_tickets_categories_id;
}

class TicketsDepartmentEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $departments_name;
	public ?array $users_id;
}

class TicketsNotificationEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $ticket_notifications_actions_gui_template;
	public string $ticket_notifications_actions_email_template;
	public bool $ticket_notifications_gui;
	public bool $ticket_notifications_email;
	public bool $ticket_notifications_notify_responsible_users;
	public bool $ticket_notifications_notify_departments;
	public string $ticket_notifications_glyphicon;
	public string $ticket_notifications_color;
	public ?string $ticket_notifications_email_subject;
}

class TicketsPriorityEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $tickets_priorities_name;
}

class TicketsStatusEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $tickets_statuses_name;
	public bool $tickets_statuses_open;
	public bool $tickets_statuses_closed;
	public string $tickets_statuses_color;
}

class TvodProductEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $tvods_products_name;
	public int $tvods_products_unit_length;
	public \Motv\Connector\Sms\Enums\Sms\TimeUnitEnum $tvods_products_unit;
	public bool $tvods_products_is_active;
	public int $tvods_products_products_groups_id;

	/** @var array<int> */
	public array $tvods;
	public ?int $tvods_products_discount;

	/** @var \DateTimeImmutable|string|null */
	public $tvods_products_discount_from;

	/** @var \DateTimeImmutable|string|null */
	public $tvods_products_discount_to;
	public array $prices;
	public ?array $tvods_products_payment_gateways;
}

class UserEntity extends \Motv\Connector\Sms\InputEntities\ApiSupport\UserEntity
{
	public ?string $users_name;
	public ?string $users_description;
	public ?int $users_departments_id;
	public ?int $users_tickets;
	public ?int $users_dealers_id;
}

class VendorEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $vendors_name;
	public bool $vendors_default;
}

class XmlColumnEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $date_start_name;
	public ?string $date_start_attribute;
	public ?string $date_end_name;
	public ?string $date_end_attribute;
	public ?string $start_name;
	public ?string $start_attribute;
	public ?string $end_name;
	public ?string $end_attribute;
	public ?string $duration_name;
	public ?string $duration_attribute;
	public string $title_name;
	public ?string $title_attribute;
	public ?string $sub_title_name;
	public ?string $sub_title_attribute;
	public ?string $description_name;
	public ?string $description_attribute;
	public ?string $rating_name;
	public ?string $rating_attribute;
	public ?string $category_name;
	public ?string $category_attribute;
	public ?string $episode_num_name;
	public ?string $episode_num_attribute;
	public ?string $icon_name;
	public ?string $icon_attribute;
	public ?string $actors_name;
	public ?string $actors_attribute;
	public ?string $director_name;
	public ?string $director_attribute;
	public ?array $other_data;
}

class XmlColumnOtherDataEntity extends \Motv\Connector\Sms\InputEntities\MotvEntity
{
	public string $other_data_name;
	public string $other_data_tag;
	public ?string $other_data_attribute;
}
